"""Schemas initialization."""
from app.schemas.base import BaseSchema, BaseResponse, MessageResponse, TokenResponse
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserLogin,
    ChangePassword,
    PasswordResetRequest,
    PasswordResetConfirm,
)
from app.schemas.finance import (
    DailyEntryBase,
    DailyEntryCreate,
    DailyEntryUpdate,
    DailyEntryResponse,
    InvestmentBase,
    InvestmentCreate,
    InvestmentUpdate,
    InvestmentResponse,
    InvestmentSummary,
    MonthlyGoalBase,
    MonthlyGoalCreate,
    MonthlyGoalUpdate,
    MonthlyGoalResponse,
    CategoryBreakdown,
    MonthlyAnalytics,
    AnnualAnalytics,
    DashboardStats,
)

__all__ = [
    "BaseSchema",
    "BaseResponse",
    "MessageResponse",
    "TokenResponse",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserLogin",
    "ChangePassword",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "DailyEntryBase",
    "DailyEntryCreate",
    "DailyEntryUpdate",
    "DailyEntryResponse",
    "InvestmentBase",
    "InvestmentCreate",
    "InvestmentUpdate",
    "InvestmentResponse",
    "InvestmentSummary",
    "MonthlyGoalBase",
    "MonthlyGoalCreate",
    "MonthlyGoalUpdate",
    "MonthlyGoalResponse",
    "CategoryBreakdown",
    "MonthlyAnalytics",
    "AnnualAnalytics",
    "DashboardStats",
]
